# Generated by Django 3.1.1 on 2020-09-07 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_post_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='principal',
            field=models.BooleanField(default=False),
        ),
    ]
